.PHONY: clean All

All:
	@echo "----------Building project:[ oop - Debug ]----------"
	@"$(MAKE)" -f  "oop.mk"
clean:
	@echo "----------Cleaning project:[ oop - Debug ]----------"
	@"$(MAKE)" -f  "oop.mk" clean
